### PR TITLE
Fix batch permissions

### LINKED ISSUE #2450: Batch Edit Permissions Tab is not working
### Descriptive summary

In SUfia 7 when I select a group of works for batch editing, and I change the permissions nothing happens and the page spins forever.

In the log I see 

```
[CANCAN] Checking edit permissions for user: blah@psu.edu with groups: ["public", "registered"]
Completed 404 Not Found in 11ms (Views: 0.2ms | ActiveRecord: 0.1ms)

```

This happens when I try to change the visibility of add an edit user.
### Expected behavior

The spinning wheels should stop and we should get changes saved on the ui.
screen shot 2016-08-10 at 12 32 26 pm
### Actual behavior

The wheels spin forever and the works do not get updated
screen shot 2016-08-10 at 12 33 14 pm
### Steps to reproduce the behavior

When I have multiple works in the system
And I go to the My Works listing
And I check the box next to two or more works
And I click on Batch Edit
And I Click on Permissions
And I change the visibility
And I click on "Save Changes"
Then I should see the spinning wheels
And I the wheels should stop (which they do not)
And "Changes Saved" should appear next to the "Save Changes" button
### Related work
#2330 Batch Edit Redesign

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #2450

### CODE REVIEW

File: app/forms/sufia/forms/batch_edit_form.rb [hunk 1]
```diff
@@ -19,6 +20,13 @@ def initialize(model, current_ability, batch)
         initialize_combined_fields(batch)
       end
 
+      # Which parameters are can we accept from the form
```
Comment (mjgiarlo) [inline app/forms/sufia/forms/batch_edit_form.rb]: `s/are can we/can we/` ?

File: spec/controllers/batch_edits_controller_spec.rb [hunk 2]
```diff
@@ -40,6 +40,7 @@
     end
 
     before do
+      # TODO: why aren't we just submitting batch_document_ids[] as a parameter?
```
Comment (mjgiarlo) [inline spec/controllers/batch_edits_controller_spec.rb]: Should we write up a Hyrax issue for this?

Comment (jcoyne) [inline spec/controllers/batch_edits_controller_spec.rb]: https://github.com/projecthydra-labs/hyrax/issues/303
