### PR TITLE
TrophyPresenter should return a title, fixes #2280

### LINKED ISSUE #2280: Work titles are not appearing correctly in highlighted works tab
### Descriptive summary

When I highlight a file on my profile
Then I do not see its title on the highlighted works tab

highlight

### Expected behavior

I should see the title.

### Actual behavior

I do not.

### Steps to reproduce the behavior

1. Create a work
1. Highlight it using the dropdown menu from the work's dashboard entry
1. Visit your profile

### PR DESCRIPTION
**Pull request by awead**
Fixes #2280 

@projecthydra/sufia-code-reviewers

### CODE REVIEW

File: app/presenters/sufia/trophy_presenter.rb [hunk 1]
```diff
@@ -18,6 +18,10 @@ def thumbnail_path
       solr_document[CatalogController.blacklight_config.index.thumbnail_field]
     end
 
+    def to_s
+      solr_document.title.first
```
Comment (cam156) [inline app/presenters/sufia/trophy_presenter.rb]: @awead I wonder if it would be better to just delegate to the solr_document. Curation concerns is already providing a to_s: https://github.com/projecthydra/curation_concerns/blob/master/app/models/concerns/curation_concerns/solr_document_behavior.rb

Comment (mjgiarlo) [inline app/presenters/sufia/trophy_presenter.rb]: :+1: to what @cam156 said.

File: spec/presenters/sufia/trophy_presenter_spec.rb [hunk 2]
```diff
@@ -16,7 +16,7 @@
   end
 
   let(:presenter) { described_class.new(solr_document) }
-  let(:solr_document) { SolrDocument.new(id: '123456', has_model_ssim: 'GenericWork') }
+  let(:solr_document) { SolrDocument.new(id: '123456', has_model_ssim: 'GenericWork', title_tesim: 'A Title') }
```
Comment (mjgiarlo) [inline spec/presenters/sufia/trophy_presenter_spec.rb]: Aren't `has_model_ssim` and `title_tesim` multi-valued fields? Should they return arrays? I'm wondering whether this expectation sets up a mismatch between what we're testing and how the app behaves.

Comment (awead) [inline spec/presenters/sufia/trophy_presenter_spec.rb]: @mjgiarlo yes, but in the end it doesn't matter since it's cast to an array anyway.

Comment (mjgiarlo) [inline spec/presenters/sufia/trophy_presenter_spec.rb]: @awead In the `SolrDocumentBehavior`, you mean, or elsewhere?

**Comment by awead** [comment]
done.

File: spec/presenters/sufia/trophy_presenter_spec.rb (hunk 2 above)
Comment (awead) [inline spec/presenters/sufia/trophy_presenter_spec.rb]: In Behavior. It does `Array.wrap` with title, so the expectation seems to be either string or array.

**Comment by cam156** [comment]
👍 waiting on travis
