### PR TITLE
Download endnote file as attachment, fixes #2694

### LINKED ISSUE #2694: Endnote export is not downloading
### Descriptive summary

When clicking the EndNote link under _Citations_ in the work show page, the endnote format is rendered in the browser, as plain text, instead of being downloaded as an `.endnote` file.

### Expected behavior

File with `.endnote` should be downloaded

### Actual behavior

Content is rendered in the page.

### Steps to reproduce the behavior

1. Create a work
1. Click "EndNote" from the work show page

### PR DESCRIPTION
**Pull request by awead**
Fixes #2694 

Downloads endnote export format as a file and provides a configurable filename via SolrDocument.

@projecthydra/sufia-code-reviewers

### CODE REVIEW

File: spec/controllers/curation_concerns/generic_works_controller_spec.rb [hunk 1]
```diff
@@ -62,9 +62,19 @@
...
     end
 
-    it 'renders an endnote file' do
-      get :show, params: { id: work, format: 'endnote' }
-      expect(response).to be_successful
+    context "with an endnote file" do
+      let(:disposition)  { response.header.fetch("Content-Disposition") }
+      let(:content_type) { response.header.fetch("Content-Type") }
+
+      render_views
```
Comment (mjgiarlo) [inline spec/controllers/curation_concerns/generic_works_controller_spec.rb]: Should this be in a `before` block?

Comment (awead) [inline spec/controllers/curation_concerns/generic_works_controller_spec.rb]: No, I thought the same as you and tried that, but RSpec doesn't let you.
