### PR TITLE
checking for members and saved before querying solr.  fixes #1216

### LINKED ISSUE #1216: Collection bytes returns an error is the Collection is not saved
If you call bytes on the collection before it is saved there is no ID to join on, therefore you get a weird solr error.  Should return a valid error like "Bytes can not be calculated until the collection has been saved"

-- Test case --- 
 
 c = Collection.new
 gf = GenericFile.new
 gf.apply_depositor_metadata "cam156"
 c.members << gf
 c.bytes

---- Error ---
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>2,'params'=>{'q'=>'_query_:"{!raw f=has_model_ssim}GenericFile"','qt'=>'standard','fl'=>'id, file_size_is','fq'=>'{!join from=hasCollectionMember_ssim to=id}id:','rows'=>'1','wt'=>'ruby'}},'error'=>{'msg'=>'org.apache.solr.search.SyntaxError: Cannot parse \'id:\': Encountered "<EOF>" at line 1, column 3.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...

URI: http://localhost:8983/solr/development/select?wt=ruby&fq=%7B%21join+from%3DhasCollectionMember_ssim+to%3Did%7Did%3A&fl=id%2C+file_size_is&rows=1&q=_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DGenericFile%22&qt=standard

Backtrace: /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response'
/Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in `execute'
/Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive'
(eval):2:in `get'
/Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/solr_service.rb:107:in `query'
/Users/cam156/sufia/sufia-models/app/models/concerns/sufia/collection_behavior.rb:30:in `bytes'
(irb):7:in `irb_binding'
/Users/cam156/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/workspace.rb:86:in `eval'
/Users/cam156/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/workspace.rb:86:in `evaluate'
/Users/cam156/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/context.rb:379:in `evaluate'
/Users/cam156/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:489:in `block (2 levels) in eval_input'
	from /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response'
	from /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in `execute'
	from /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive'
	from (eval):2:in `get'
	from /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/solr_service.rb:107:in `query'
	from /Users/cam156/sufia/sufia-models/app/models/concerns/sufia/collection_behavior.rb:30:in `bytes'
	from (irb):7
	from /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/cam156/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

### PR DESCRIPTION
**Pull request by cam156**

### CODE REVIEW

File: spec/models/collection_spec.rb [hunk 1]
```diff
@@ -21,7 +21,9 @@
   describe "::bytes" do
     subject { @collection.bytes }
     context "with no items" do
-      before { @collection.save }
+      before do
+        expect(ActiveFedora::SolrService).not_to receive(:query)
```
Comment (mjgiarlo) [inline spec/models/collection_spec.rb]: Should this be an `allow`, or do you want to run a test in the `before` block?

File: spec/models/collection_spec.rb [hunk 2]
```diff
@@ -44,7 +46,17 @@
         allow(@collection).to receive(:members).and_return([file, file, file])
         allow(ActiveFedora::SolrService).to receive(:query).with(query, args).and_return(documents)
       end
-      it { is_expected.to eq 99 }
+
+      context "saved" do
```
Comment (mjgiarlo) [inline spec/models/collection_spec.rb]: With `context` blocks, it can improve readability of output to start the string with "with" or "when", so:

```ruby
context "when saved" do
  # ...
end
```

File: spec/models/collection_spec.rb [hunk 3]
```diff
@@ -44,7 +46,17 @@
...
+        before do
+          allow(@collection).to receive(:new_record?).and_return(false)
+        end
+        it { is_expected.to eq 99 }
+      end
+
+      context "not saved" do
```
Comment (mjgiarlo) [inline spec/models/collection_spec.rb]: Can you change this to "when not saved"?

File: spec/models/collection_spec.rb [hunk 4]
```diff
@@ -44,7 +46,17 @@
...
+        it { expect {subject}.to raise_error RuntimeError }
```
Comment (mjgiarlo) [inline spec/models/collection_spec.rb]: Simplify to:

```ruby
it { is_expected.to raise_error RuntimeError }
```

File: sufia-models/app/models/concerns/sufia/collection_behavior.rb [hunk 5]
```diff
@@ -18,13 +18,19 @@ def update_permissions
     # Compute the sum of each file in the collection using Solr to
     # avoid having to hit Fedora 
     #
-    # Returns an integer 
+    # @return [Integer] size of collection in bytes
+    # @raise [RuntimeError] unsaved record does not exist in solr
```
Comment (mjgiarlo) [inline sufia-models/app/models/concerns/sufia/collection_behavior.rb]: :clap: Yay for YARD!

File: spec/models/collection_spec.rb (hunk 4 above)
Comment (mjgiarlo) [inline spec/models/collection_spec.rb]: Can you also add the "Record must be saved to query for bytes" string here to make sure you're catching the right `RuntimeError`?

File: sufia-models/app/models/concerns/sufia/collection_behavior.rb [hunk 6]
```diff
@@ -18,13 +18,19 @@ def update_permissions
...
     def bytes
+      rows = members.count
+      return 0 if rows == 0
+
+      raise "Record must be saved to query for bytes" if new_record?
```
Comment (mjgiarlo) [inline sufia-models/app/models/concerns/sufia/collection_behavior.rb]: How about "Collection must be saved before querying for bytes"?

File: spec/models/collection_spec.rb (hunk 4 above)
Comment (cam156) [inline spec/models/collection_spec.rb]: Your first line does not work.  The error gets raise on the subject line and never caught.  That was the first syntax I tried, and then banged my head trying to get one that works.

**Comment by cam156** [comment]
@mjgiarlo Thanks for the comments.  I fixed where appropriate.

File: spec/models/collection_spec.rb [hunk 7]
```diff
@@ -44,7 +46,17 @@
...
+
+      context "when saved" do
+        before do
+          allow(@collection).to receive(:new_record?).and_return(false)
+        end
+        it { is_expected.to eq 99 }
+      end
+
+      context "when not saved" do
+        it { expect {subject}.to raise_error "Collection must be saved to query for bytes" }
```
Comment (mjgiarlo) [inline spec/models/collection_spec.rb]: If the `is_expected` syntax doesn't work (weird!), I'd say tweak the syntax a bit here:

```ruby
it "raises an error" do
  expect { subject }.to raise_error "Collection must be saved to query for bytes"
end
```

Because the "it { expect" syntax isn't used anywhere else in Sufia.

File: sufia-models/app/models/concerns/sufia/collection_behavior.rb [hunk 8]
```diff
@@ -18,13 +18,19 @@ def update_permissions
     # Compute the sum of each file in the collection using Solr to
     # avoid having to hit Fedora 
     #
-    # Returns an integer 
+    # @return [Integer] size of collection in bytes
```
Comment (jcoyne) [inline sufia-models/app/models/concerns/sufia/collection_behavior.rb]: Fixnum rather than Integer

File: spec/models/collection_spec.rb [hunk 9]
```diff
@@ -44,7 +46,19 @@
...
+
+      context "when saved" do
+        before do
+          allow(@collection).to receive(:new_record?).and_return(false)
+        end
+        it { is_expected.to eq 99 }
+      end
+
+      context "when not saved" do
+        it "raises and error" do
```
Comment (mjgiarlo) [inline spec/models/collection_spec.rb]: `s/and/an/`

**Comment by mjgiarlo** [comment]
:+1:
