### PR TITLE
Rough surgical backport of projecthydra-labs/hyrax#477

### LINKED ISSUE #3098: Sufia::PermissionTemplate error on save work
### Descriptive summary
Related to Sufia 7.3

### Expected behavior
Can save work
### Actual behavior
Cannot save work - Sufia::PermissionTemplate is empty
https://gist.github.com/njaffer/d6142654da25c9e0148499fb45c8bf9a
### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #3098

@projecthydra/sufia-code-reviewers

### CODE REVIEW

File: app/services/sufia/admin_set_create_service.rb [hunk 1]
```diff
@@ -1,6 +1,21 @@
 module Sufia
   # Creates AdminSets
   class AdminSetCreateService
+    DEFAULT_ID = 'admin_sets/default'.freeze
```
Comment (mjgiarlo) [inline app/services/sufia/admin_set_create_service.rb]: Yes, this knowledge lives in two places. I don't love it but I don't want to commit to more refactoring to fix #3098.

Comment (jeremyf) [inline app/services/sufia/admin_set_create_service.rb]: Is there an "absolution" emoji?

Comment (mjgiarlo) [inline app/services/sufia/admin_set_create_service.rb]: :laughing:
