### PR TITLE
i18n errors fixed

### LINKED ISSUE #2064: Batch upload sidebar title problem - untranslated key
http://localhost:3000/batch_uploads/new

- Sidebar title is "Header" (untranslated key)

screen shot 2016-05-19 at 6 38 44 pm

Similar format issues for file upload page.

### PR DESCRIPTION
**Pull request by jenlindner**
Fixes #2064 ; refs #2063 

Added or corrected missing keys to en.sufia.yml, added config to test_app_generator to raise translation errors in dev and test environments to catch them in the future. Also fixed up a few tests, helpers and views with key problems. One issue in one test solved with a hack in the locale.yml though: 

```
    test:
      progress:
        header: "Test Header Title"
```
Changes proposed in this pull request:
* config change to raise translation key errors in test and dev
* fixes for problematic keys in views tests and helper methods
* added keys to locale .yml

@projecthydra/sufia-code-reviewers

### CODE REVIEW

File: spec/helpers/generic_work_helper_spec.rb [hunk 1]
```diff
@@ -22,11 +22,11 @@
       it 'renders a list of links to the collections' do
         expect(helper.render_collection_links(work_doc)).to match(/Is part of/i)
 
-        expect(helper.render_collection_links(work_doc)).to match("href=\"/collections/#{coll_ids[0]}\"")
-        expect(helper.render_collection_links(work_doc)).to match("href=\"/collections/#{coll_ids[1]}\"")
+        expect(helper.render_collection_links(work_doc)).to include("href=&quot;/collections/#{coll_ids[0]}&quot;")
```
Comment (jcoyne) [inline spec/helpers/generic_work_helper_spec.rb]: This doesn't seem right to me. Can you explain why it's changed?

File: app/helpers/generic_work_helper.rb [hunk 2]
```diff
@@ -5,6 +5,6 @@ def render_collection_links(solr_doc)
     links = collection_list.map do |collection|
       link_to collection.title_or_label, collection_path(collection.id)
     end
-    content_tag :span, t(:is_part_of) + ': ' + links.join(', ').html_safe
+    content_tag :span, t('sufia.collection.is_part_of') + ': ' + links.join(', ')
```
Comment (jcoyne) [inline app/helpers/generic_work_helper.rb]: I think that `html_safe` was required. That's why the test changed below. Can you please add that back or use [safe_join](http://api.rubyonrails.org/classes/ActionView/Helpers/OutputSafetyHelper.html#method-i-safe_join)?

**Comment by jcoyne** [comment]
Very good work. Please address that html safety concern and it looks good.

File: app/helpers/generic_work_helper.rb (hunk 2 above)
Comment (jenlindner) [inline app/helpers/generic_work_helper.rb]: I really dislike this too but html_safe wasn't doing the escaping, and I read that content_tag provides it so thought to just remove it and re-write the expected output to match what the helper is creating. :/

Same results this morning, the escaping still occurs with either html_safe or safe_join(links). 
```
content_tag :span, t('sufia.collection.is_part_of') + ': ' + links.join(', ').html_safe
(byebug) helper.render_collection_links(work_doc)
"<span>Is part of: &lt;a href=&quot;/collections/111&quot;&gt;Collection 111&lt;/a&gt;, &lt;a href=&quot;/collections/222&quot;&gt;Collection 222&lt;/a&gt;</span>"


content_tag :span, t('sufia.collection.is_part_of') + ': ' + safe_join(links)

(byebug) helper.render_collection_links(work_doc)
"<span>Is part of: &lt;a href=&quot;/collections/111&quot;&gt;Collection 111&lt;/a&gt;&lt;a href=&quot;/collections/222&quot;&gt;Collection 222&lt;/a&gt;</span>"
```
I'm not sure how to prevent that escaping.

Comment (jcoyne) [inline app/helpers/generic_work_helper.rb]: Here's why it's different (but I don't understand why)
```ruby
(byebug) (t(:is_part_of) + ': ' ).html_safe?
true
(byebug) (t('sufia.collection.is_part_of') + ': ').html_safe?
false
```

Comment (jcoyne) [inline app/helpers/generic_work_helper.rb]: More by way of explanation:
```
(byebug) t(:is_part_of).html_safe?
true
(byebug) t('sufia.collection.is_part_of').html_safe?
false
```

Comment (jcoyne) [inline app/helpers/generic_work_helper.rb]: Can you change it to this?
```ruby
safe_join([t('sufia.collection.is_part_of'), ': '] + links)
```

Comment (jenlindner) [inline app/helpers/generic_work_helper.rb]: Yes, that's great! Done.

**Comment by jcoyne** [comment]
I'll restart the build after #2103 is merged.

**Comment by mjgiarlo** [comment]
@jenlindner #2103 is close to being merged (if Travis is :smile:), at which point you should rebase on the latest in master and push that up. That *should* sort this PR out.

**Comment by jcoyne** [comment]
@jenlindner yep, what Mike said. Go ahead and rebase now, and it should probably pass.

**Comment by jenlindner** [comment]
Sweet! I'll do that :)
