### PR TITLE
Switched fixed position from top to bottom for better results…

### LINKED ISSUE #1719: Affix the create a new work status panel to the screen
So that it doesn't move when you scroll.

Consider: 
- [ ] mobile screen sizes
- [ ] viewport is shorter than the status panel.

Ref #1562

### PR DESCRIPTION
**Pull request by mtribone**
Fixes #1719  ; refs #1562 

Adds polyfill JS to the sidebar to fix or stick save/visibility widget to the bottom of the browser. Best on desktop. Needs more work with responsiveness of overall design. 

Changes proposed in this pull request:
*  Add JS to apps.js
*  Adds additional JS to handle rendering
*  Makes save/visibility sidebar stick to the bottom of the browser

@projecthydra/sufia-code-reviewers

...and matchched column width for left offset from Bootstrap. Removed extra class and replaced pixel values with em and percent and created variables for the values in settings.scs. TODO address responsive media queriess

### CODE REVIEW

**Comment by mtribone** [comment]
screen shot 2016-04-22 at 12 52 30 pm

**Comment by mtribone** [comment]
screen shot 2016-04-22 at 12 52 49 pm

File: app/assets/javascripts/sufia/fixedsticky.js [hunk 1]
```diff
@@ -0,0 +1,193 @@
...
+					}
+				});
+			});
+		}
+	};
+
+	win.FixedSticky = S;
+
+	// Plugin
+	$.fn.fixedsticky = function( method ) {
```
Comment (jcoyne) [inline app/assets/javascripts/sufia/fixedsticky.js]: If this isn't code that you wrote, it should be in `vendor/assets/javascripts/fixedsticky.js`

File: app/assets/javascripts/sufia/app.js [hunk 2]
```diff
@@ -12,6 +12,8 @@ Sufia = {
   saveWorkControl: function() {
     var sw = require('sufia/save_work/save_work_control');
     new sw.SaveWorkControl($("#form-progress")).activate();
+      FixedSticky.tests.sticky = false;
```
Comment (cbeer) [inline app/assets/javascripts/sufia/app.js]: Is this really a property of the save work control, or does it deserve extracting to something generally reusable?

I wonder too about using `#fixedwidget` vs `.fixedsticky`.

File: app/assets/javascripts/sufia/fixedsticky.js [hunk 3]
```diff
@@ -0,0 +1,193 @@
+;(function( win, $ ) {
```
Comment (cbeer) [inline app/assets/javascripts/sufia/fixedsticky.js]: Is this our code, or should it be vendorized?

File: lib/sufia/engine.rb [hunk 4]
```diff
@@ -60,6 +60,7 @@ class Engine < ::Rails::Engine
       app.config.assets.precompile << /fontawesome-webfont\.(?:svg|ttf|woff)$/
       app.config.assets.precompile += %w( ZeroClipboard.swf )
       app.config.assets.precompile += %w(*.png *.jpg *.ico *.gif *.svg)
+      app.config.assets.precompile += %w( fixedsticky.js )
```
Comment (jcoyne) [inline lib/sufia/engine.rb]: This line can be omitted.

File: app/views/curation_concerns/base/_form_progress.html.erb [hunk 5]
```diff
@@ -1,4 +1,5 @@
-    <aside class="form-progress panel panel-default" id="form-progress">
+<div id="form-progress">
+<aside class="form-progress panel panel-default">
```
Comment (jcoyne) [inline app/views/curation_concerns/base/_form_progress.html.erb]: please balance the indent with the closing tag.

File: app/views/curation_concerns/base/_form.html.erb [hunk 6]
```diff
@@ -1,4 +1,5 @@
 <%= simple_form_for [main_app, @form], html: { multipart: true } do |f| %>
+    <div class="row">
   <div class="col-xs-12 col-sm-8" role="main">
```
Comment (jcoyne) [inline app/views/curation_concerns/base/_form.html.erb]: Please balance the indent.

File: app/assets/stylesheets/sufia/_fixedsticky.scss [hunk 7]
```diff
@@ -0,0 +1,28 @@
+.fixedsticky {
```
Comment (cbeer) [inline app/assets/stylesheets/sufia/_fixedsticky.scss]: Same question. This seems like a mixed of upstream styles and our own? Should we split the upstream stuff into vendor?

File: app/assets/stylesheets/sufia/_fixedsticky.scss [hunk 8]
```diff
@@ -0,0 +1,28 @@
...
+/* When position: sticky is supported but native behavior is ignored */
+.fixedsticky-withoutfixedfixed .fixedsticky-off,
+.fixed-supported .fixedsticky-off {
+  position: static;
+}
+
+.fixedsticky-withoutfixedfixed .fixedsticky-on,
+.fixed-supported .fixedsticky-on {
+  position: fixed;
+  left: $save-viz-widget-left;
```
Comment (cbeer) [inline app/assets/stylesheets/sufia/_fixedsticky.scss]: This seems like properties of the save widget -- maybe it should only style the save widget and not every fixedsticky?

File: app/assets/javascripts/sufia/app.js [hunk 9]
```diff
@@ -12,6 +12,8 @@ Sufia = {
...
+      $('#fixedwidget').fixedsticky();
```
Comment (jcoyne) [inline app/assets/javascripts/sufia/app.js]: Should this go into `save_work_control.es6`?

File: app/views/curation_concerns/base/_form.html.erb [hunk 10]
```diff
@@ -1,4 +1,5 @@
 <%= simple_form_for [main_app, @form], html: { multipart: true } do |f| %>
+    <div class="row">
```
Comment (cbeer) [inline app/views/curation_concerns/base/_form.html.erb]: Even though it'll be a lot of changed lines, I'd like to see us have consistent indentation in this partial. Can we indent the inner content of this new row?

File: app/assets/javascripts/sufia/app.js (hunk 9 above)
Comment (jcoyne) [inline app/assets/javascripts/sufia/app.js]: On second thought, this should not go into `save_work_control.es6`, but it should be within a new method in this file.

File: app/views/curation_concerns/base/_form_progress.html.erb [hunk 11]
```diff
@@ -1,4 +1,5 @@
-    <aside class="form-progress panel panel-default" id="form-progress">
+<div id="form-progress">
```
Comment (cbeer) [inline app/views/curation_concerns/base/_form_progress.html.erb]: Same comment as above; could we fix up all the indentation?

File: lib/sufia/engine.rb (hunk 4 above)
Comment (cbeer) [inline lib/sufia/engine.rb]: Why do we need this explicit precompile?

File: app/assets/stylesheets/sufia/_fixedsticky.scss (hunk 7 above)
Comment (jcoyne) [inline app/assets/stylesheets/sufia/_fixedsticky.scss]: fixedsticky dosen't provide/maintain this, but they show this as an example of how to style it.

Comment (mtribone) [inline app/assets/stylesheets/sufia/_fixedsticky.scss]: It still might be important to split them up.

File: app/assets/stylesheets/sufia/_fixedsticky.scss (hunk 8 above)
Comment (mtribone) [inline app/assets/stylesheets/sufia/_fixedsticky.scss]: Yeah I'll split these up so that it only affects the save visibility widget

File: app/assets/stylesheets/sufia/_form-progress.scss [hunk 12]
```diff
@@ -47,3 +47,9 @@ aside.form-progress {
     }
   }
 }
+
```
Comment (mtribone) [inline app/assets/stylesheets/sufia/_form-progress.scss]: Moved the custom CSS from fixedsticky to here and added another class to target the save widget and not all fixedsticky elements

File: app/assets/stylesheets/sufia/_sufia.scss [hunk 13]
```diff
@@ -6,7 +6,7 @@
         'sufia/collections', 'sufia/batch-edit', 'sufia/dashboard', 'sufia/home-page',
         'sufia/featured', 'sufia/usage-stats', 'sufia/catalog', 'sufia/buttons',
         'sufia/tinymce', 'sufia/proxy-rights', 'sufia/file-show', 'sufia/work-show',
-        'sufia/modal', 'sufia/form-progress';
+        'sufia/modal', 'sufia/form-progress', '../../../../vendor/assets/stylesheets/fixedsticky';
```
Comment (jcoyne) [inline app/assets/stylesheets/sufia/_sufia.scss]: This seems awful.  Can we just include it using sprockets?

File: app/views/curation_concerns/base/_form_progress.html.erb [hunk 14]
```diff
@@ -1,44 +1,46 @@
-    <aside class="form-progress panel panel-default" id="form-progress">
-      <div class="panel-heading">
-        <h2><%= t("sufia.#{controller_name}.progress.header") %></h2>
+<div id="form-progress">
```
Comment (jcoyne) [inline app/views/curation_concerns/base/_form_progress.html.erb]: Why are you adding this div?

File: app/assets/stylesheets/sufia/_sufia.scss (hunk 13 above)
Comment (mtribone) [inline app/assets/stylesheets/sufia/_sufia.scss]: Yeah it is kinda ugly, right? I'll pop it back into sufia/fixedsticky

File: app/views/curation_concerns/base/_form_progress.html.erb (hunk 14 above)
Comment (mtribone) [inline app/views/curation_concerns/base/_form_progress.html.erb]: Ah. A remnant of another technique where I was trying to call a parent div and ended up using an ID from the template. Will remove. Thx
