### PR TITLE
Auto-link description field, fixes #2348

### LINKED ISSUE #2348: Description Field Ouput in Search List Contains Code and Text
### Descriptive summary

When I create a new work in Sufia 7.0.0 and then search all of sufia, the description field output in the results contain code and text.

### Expected behavior

I expect just human readable text as the output of the description field.

### Actual behavior

screen shot 2016-07-11 at 12 39 49 pm

### Steps to reproduce the behavior

1. Create a work
1. Work show page
1. Search bar > all of sufia > go

### Related work

https://github.com/projecthydra/sufia/issues/2309

### PR DESCRIPTION
**Pull request by awead**
Fixes #2348 

Links in the description field now display properly.

desc

@projecthydra/sufia-code-reviewers

### CODE REVIEW

File: app/helpers/sufia/sufia_helper_behavior.rb [hunk 1]
```diff
@@ -121,13 +121,18 @@ def index_field_link(options)
...
+    #
+    # @param [String,Hash] text string to format and escape or a hash as per helper_method
+    # @param text [SolrDocument] :document
+    # @param text [String] :field name of the solr field
+    # @param text [Blacklight::Configuration::IndexField, Blacklight::Configuration::ShowField] :config
+    # @param text [Array] :value array of values for the field
     # @param show_link [Boolean]
     # @return [ActiveSupport::SafeBuffer]
     # @todo stop being a helper_method, start being part of the Blacklight render stack?
     def iconify_auto_link(text, show_link = true)
```
Comment (jcoyne) [inline app/helpers/sufia/sufia_helper_behavior.rb]: Can we choose a better variable name than`text`

File: app/helpers/sufia/sufia_helper_behavior.rb [hunk 2]
```diff
@@ -121,13 +121,18 @@ def index_field_link(options)
...
 
-    # *Sometimes* a Blacklight helper_method
-    # @param text [String,Hash] string to format and escape or a hash as per helper_method
+    # Uses Rails auto_link to add links to fields
+    #
+    # @param [String,Hash] text string to format and escape or a hash as per helper_method
+    # @param text [SolrDocument] :document
+    # @param text [String] :field name of the solr field
+    # @param text [Blacklight::Configuration::IndexField, Blacklight::Configuration::ShowField] :config
+    # @param text [Array] :value array of values for the field
```
Comment (jcoyne) [inline app/helpers/sufia/sufia_helper_behavior.rb]: These should be `@option` not `@param`

File: app/helpers/sufia/sufia_helper_behavior.rb [hunk 3]
```diff
@@ -121,13 +121,18 @@ def index_field_link(options)
...
     # @param show_link [Boolean]
     # @return [ActiveSupport::SafeBuffer]
     # @todo stop being a helper_method, start being part of the Blacklight render stack?
     def iconify_auto_link(text, show_link = true)
-      text = index_presenter(text[:document]).field_value(text[:config].key, text[:config]) if text.is_a? Hash
+      text = index_presenter(text[:document]).field_value(text[:field].to_sym, text[:config]) if text.is_a? Hash
```
Comment (jcoyne) [inline app/helpers/sufia/sufia_helper_behavior.rb]: `field_value` expects a string, why are you casting to a symbol? See https://github.com/projectblacklight/blacklight/blob/master/spec/presenters/index_presenter_spec.rb#L43

File: app/helpers/sufia/sufia_helper_behavior.rb (hunk 2 above)
Comment (awead) [inline app/helpers/sufia/sufia_helper_behavior.rb]: even if they're required keys in the hash, and not optional?

File: app/helpers/sufia/sufia_helper_behavior.rb (hunk 3 above)
Comment (awead) [inline app/helpers/sufia/sufia_helper_behavior.rb]: It doesn't render if I don't call .to_sym. I get the error that @mtribone describes.

File: spec/helpers/sufia_helper_spec.rb [hunk 4]
```diff
@@ -233,16 +237,16 @@ def create_models(model, user1, user2)
...
-      let(:conf) { blacklight_config.index_fields['description_tesim'] }
-      subject { helper.iconify_auto_link(document: document, value: text, config: conf) }
-      it do
-        pending 'Need a different way to test description'
-        is_expected.to eq '<span>Foo &lt; <a href="http://www.example.com"><span class="glyphicon glyphicon-new-window"></span> http://www.example.com</a>. &amp; More text</span>'
+
+    context "when using a hash argument" do
+      subject { helper.iconify_auto_link(arg) }
+      describe "auto-linking in the title" do
+        let(:arg) { { document: document, value: text, config: blacklight_config.index_fields['title_tesim'], field: 'title_tesim' } }
```
Comment (jcoyne) [inline spec/helpers/sufia_helper_spec.rb]: It seems like this test is reaching beyond the scope of a unit test.  Shouldn't it just expect that the `IndexPresenter#field_value` is called with the correct values?

Comment (awead) [inline spec/helpers/sufia_helper_spec.rb]: This is what is getting passed to the method when the index view is rendered.

File: app/helpers/sufia/sufia_helper_behavior.rb (hunk 2 above)
Comment (jcoyne) [inline app/helpers/sufia/sufia_helper_behavior.rb]: Yes, see http://www.rubydoc.info/gems/yard/file/docs/Tags.md#option

Comment (jcoyne) [inline app/helpers/sufia/sufia_helper_behavior.rb]: Yes.

File: app/helpers/sufia/sufia_helper_behavior.rb (hunk 3 above)
Comment (jcoyne) [inline app/helpers/sufia/sufia_helper_behavior.rb]: Which error is that?

File: app/helpers/sufia/sufia_helper_behavior.rb [hunk 5]
```diff
@@ -121,13 +121,18 @@ def index_field_link(options)
       safe_join(values.map { |item| link_to_field(name, item, item) }, ", ".html_safe)
     end
 
-    # *Sometimes* a Blacklight helper_method
-    # @param text [String,Hash] string to format and escape or a hash as per helper_method
+    # Uses Rails auto_link to add links to fields
+    #
+    # @param [String,Hash] text string to format and escape or a hash as per helper_method
```
Comment (jcoyne) [inline app/helpers/sufia/sufia_helper_behavior.rb]: It looks like `text` comes before the type (I've been doing it wrong all along) http://www.rubydoc.info/gems/yard/file/docs/Tags.md#param

**Comment by jcoyne** [comment]
@awead why did you close this? Isn't it still an issue?

**Comment by awead** [comment]
@jcoyne #2352 should fix this.

**Comment by jcoyne** [comment]
But that PR was against the branch of your PR

File: app/helpers/sufia/sufia_helper_behavior.rb (hunk 5 above)
Comment (awead) [inline app/helpers/sufia/sufia_helper_behavior.rb]: It's unclear. In the options example, it's the other way around:
http://www.rubydoc.info/gems/yard/file/docs/Tags.md#option

**Comment by awead** [comment]
@jcoyne this is good to go

**Comment by jcoyne** [comment]
@awead something broke in your last change.

File: app/helpers/sufia/sufia_helper_behavior.rb [hunk 6]
```diff
@@ -121,13 +121,21 @@ def index_field_link(options)
...
-    def iconify_auto_link(text, show_link = true)
-      text = index_presenter(text[:document]).field_value(text[:config].key, text[:config]) if text.is_a? Hash
+    def iconify_auto_link(field, show_link = true)
+      if field.is_a? Hash
+        options = field[:config].separator_options || {}
+        text = field[:value].to_sentence(options)
+      end
       # this block is only executed when a link is inserted;
       # if we pass text containing no links, it just returns text.
       auto_link(html_escape(text)) do |value|
```
Comment (jcoyne) [inline app/helpers/sufia/sufia_helper_behavior.rb]: `text` is never assigned if `field` is a String

**Comment by awead** [comment]
@jcoyne OK, fixed now.

File: app/helpers/sufia/sufia_helper_behavior.rb [hunk 7]
```diff
@@ -121,13 +121,23 @@ def index_field_link(options)
...
+    # @option field [String] :field name of the solr field
+    # @option field [Blacklight::Configuration::IndexField, Blacklight::Configuration::ShowField] :config
+    # @option field [Array] :value array of values for the field
     # @param show_link [Boolean]
     # @return [ActiveSupport::SafeBuffer]
     # @todo stop being a helper_method, start being part of the Blacklight render stack?
-    def iconify_auto_link(text, show_link = true)
-      text = index_presenter(text[:document]).field_value(text[:config].key, text[:config]) if text.is_a? Hash
+    def iconify_auto_link(field, show_link = true)
+      if field.is_a? Hash
```
Comment (jcoyne) [inline app/helpers/sufia/sufia_helper_behavior.rb]: had I written this, I would have done:
```ruby
text = case field
           when Hash
             options = field[:config].separator_options || {}
             field[:value].to_sentence(options)
           else
             field
           end
```

Not a big deal though.
